import musicImg from "../../assets/events/event-music.jpg";
import techImg from "../../assets/events/event-tech.jpg";
import comedyImg from "../../assets/events/event-comedy.jpg";
import workshopImg from "../../assets/events/event-workshop.jpg";
import conferenceImg from "../../assets/events/event-conference.jpg";
import sportsImg from "../../assets/events/event-sports.jpg";
import bannerHeroImg from "../../assets/organizer/0b2568d2a1321299cd93ab73936efb2e8bc467fe.png";

export const ORGANIZER_EVENTS = [
  {
    id: 1,
    name: "Sunfield Music Festival 2026",
    short: "Sunfield…",
    date: "15 Sep 2026",
    venue: "Bengaluru",
    sold: 856,
    total: 1000,
    pct: 86,
    revenue: "₹6,25,000",
    status: "PUBLISHED",
    statusColor: "published",
    category: "Music",
    ageRestriction: "18+",
    visibility: "PUBLIC",
    image: bannerHeroImg || musicImg,
    thumbnail: musicImg,
    timeRange: "04:00 PM – 11:00 PM",
    duration: "7 Hours",
    isAllDay: false,
    locationType: "PHYSICAL",
    venueDetails: {
      name: "Palace Grounds, Main Arena",
      address: "Gate 4, Bellary Road, Jayamahal",
      city: "Bengaluru",
      state: "Karnataka",
      postalCode: "560006",
      country: "India",
      googlePlaceId: "ChIJbU60yXAWrjsR4E9-UejW3_g",
    },
    description:
      "Join us for Sunfield Music Festival 2026, Bangalore's premier open-air electronic and indie music festival. Bringing together global touring headliners, sensational indie breakthrough acts, immersive visual installations, craft food villages, and an unforgettable celebration of sound and community under the open sky.",
    highlights: [
      "Multi-stage high-definition audio-visual experience",
      "Over 18 international & regional indie music performers",
      "Curated artisanal food village & craft beverage counters",
      "Exclusive VIP lounge with elevated viewing deck and fast-track lanes",
    ],
    rules:
      "1. Valid government-issued photo ID required for entry.\n2. Outside food, drinks, and professional recording equipment are prohibited.\n3. Re-entry is not permitted after exit.\n4. Zero tolerance policy for illicit substances.",
    attendeeInformation:
      "Gates open at 03:00 PM. We recommend arriving early to avoid security queues. Free water refilling stations available throughout the arena. Parking space is available at Gate 2 on a first-come, first-served basis.",
    ticketTypes: [
      {
        id: "tt-1",
        name: "Early Bird General Admission",
        price: "₹499",
        capacity: 300,
        sold: 300,
        status: "Sold Out",
        description: "Standard single entry pass with access to all outdoor music stages.",
      },
      {
        id: "tt-2",
        name: "Phase 1 General Admission",
        price: "₹699",
        capacity: 400,
        sold: 380,
        status: "Selling Fast",
        description: "General admission pass with full access to festival grounds.",
      },
      {
        id: "tt-3",
        name: "VIP Experience Pass",
        price: "₹1,499",
        capacity: 300,
        sold: 176,
        status: "Available",
        description: "Priority fast-track entry, elevated VIP lounge access, and complimentary refreshments.",
      },
    ],
    cancellationPolicy: {
      allowed: true,
      deadline: "48 hours before event",
      refundPolicy: "FULL",
      refundPercentage: 100,
      lastCancellationDate: "13 Sep 2026, 04:00 PM",
    },
    contactInformation: {
      name: "Arjun Kumar",
      phone: "+91 98765 43210",
      email: "arjun.kumar@eventhub.com",
    },
  },
  {
    id: 2,
    name: "Tech Summit Bengaluru",
    short: "Tech…",
    date: "28 Sep 2026",
    venue: "Bengaluru",
    sold: 392,
    total: 500,
    pct: 78,
    revenue: "₹3,14,000",
    status: "PUBLISHED",
    statusColor: "published",
    category: "Technology",
    ageRestriction: "All Ages",
    visibility: "PUBLIC",
    image: techImg,
    thumbnail: techImg,
    timeRange: "09:00 AM – 06:00 PM",
    duration: "9 Hours",
    isAllDay: false,
    locationType: "PHYSICAL",
    venueDetails: {
      name: "Convention Center Hall A",
      address: "Outer Ring Road, Marathahalli",
      city: "Bengaluru",
      state: "Karnataka",
      postalCode: "560103",
      country: "India",
    },
    description:
      "A flagship technology gathering for founders, developers, engineering managers, and venture investors. Deep dive into scalable cloud systems, applied generative AI, modern frontend architectures, and high-growth venture strategies.",
    highlights: [
      "Keynotes from Fortune 500 engineering leaders",
      "Hands-on architectural breakout workshops",
      "Dedicated startup expo & investor matchmaking pavilion",
    ],
    rules:
      "1. Business casual or smart casual attire recommended.\n2. Badges must be worn at all times within the convention halls.",
    attendeeInformation:
      "Conference check-in opens at 08:00 AM. Breakfast and networking lunch buffet are provided for all ticket holders.",
    ticketTypes: [
      {
        id: "tt-201",
        name: "Standard Delegate Pass",
        price: "₹799",
        capacity: 350,
        sold: 310,
        status: "Available",
        description: "Access to all keynote stages, tech expo, lunch buffet, and event kit.",
      },
      {
        id: "tt-202",
        name: "Executive & Founder Pass",
        price: "₹1,999",
        capacity: 150,
        sold: 82,
        status: "Available",
        description: "Includes VIP dinner access and exclusive investor matchmaking sessions.",
      },
    ],
    cancellationPolicy: {
      allowed: true,
      deadline: "7 days before event",
      refundPolicy: "FULL",
      refundPercentage: 100,
      lastCancellationDate: "21 Sep 2026, 09:00 AM",
    },
    contactInformation: {
      name: "Arjun Kumar",
      phone: "+91 98765 43210",
      email: "contact@techsummitblr.org",
    },
  },
  {
    id: 3,
    name: "Comedy Night Kochi",
    short: "Comedy…",
    date: "10 Oct 2026",
    venue: "Kochi",
    sold: 0,
    total: 300,
    pct: 0,
    revenue: "₹0",
    status: "DRAFT",
    statusColor: "draft",
    category: "Comedy",
    ageRestriction: "16+",
    visibility: "PRIVATE",
    image: comedyImg,
    thumbnail: comedyImg,
    timeRange: "07:30 PM – 10:00 PM",
    duration: "2.5 Hours",
    isAllDay: false,
    locationType: "PHYSICAL",
    venueDetails: {
      name: "The Laugh Cellar Marine Drive",
      address: "Marine Drive Promenade",
      city: "Kochi",
      state: "Kerala",
      postalCode: "682031",
      country: "India",
    },
    description:
      "An evening of standup comedy featuring regional Malayalam and English comedians. Prepare for 2.5 hours of unadulterated laughs, sharp observational satire, and punchy crowd work in Kochi's favorite comedy cellar.",
    highlights: [
      "4 premier headliners & special surprise guest",
      "Intimate club seating layout with front-row table service",
      "Beverages and snack counters available during intermission",
    ],
    rules:
      "1. Mobile phones must remain on silent during performances.\n2. Heckling or disruptive behavior will lead to eviction without refund.",
    attendeeInformation:
      "Doors open 45 minutes prior to showtime. Seating is on a first-come, first-served basis within allocated sections.",
    ticketTypes: [
      {
        id: "tt-301",
        name: "General Admission",
        price: "₹350",
        capacity: 200,
        sold: 0,
        status: "Draft",
        description: "Standard club entry.",
      },
      {
        id: "tt-302",
        name: "Front Row Couple Table",
        price: "₹900",
        capacity: 100,
        sold: 0,
        status: "Draft",
        description: "Reserved table seating for two with direct stage view.",
      },
    ],
    cancellationPolicy: {
      allowed: true,
      deadline: "24 hours before event",
      refundPolicy: "FULL",
      refundPercentage: 100,
      lastCancellationDate: "09 Oct 2026, 07:30 PM",
    },
    contactInformation: {
      name: "Arjun Kumar",
      phone: "+91 98765 43210",
      email: "info@laughcellarkochi.com",
    },
  },
  {
    id: 4,
    name: "AI & Cloud Builders Expo 2026",
    short: "AI & Cloud…",
    date: "27 Sep 2026",
    venue: "Hyderabad",
    sold: 480,
    total: 500,
    pct: 96,
    revenue: "₹4,80,000",
    status: "ONGOING",
    statusColor: "ongoing",
    category: "Technology",
    ageRestriction: "All Ages",
    visibility: "PUBLIC",
    image: techImg,
    thumbnail: techImg,
    timeRange: "10:00 AM – 07:00 PM",
    duration: "9 Hours",
    isAllDay: false,
    locationType: "PHYSICAL",
    venueDetails: {
      name: "HITEC City Trade Center",
      address: "Madhapur, HITEC City",
      city: "Hyderabad",
      state: "Telangana",
      postalCode: "500081",
      country: "India",
    },
    description:
      "Live interactive demonstration hall and developer showcase highlighting generative AI agents, vector databases, and real-time distributed infrastructure.",
    highlights: ["Live agent building workshops", "Hardware demo kiosks", "Over 50 tech startups exhibiting"],
    rules: "Professional conduct required. Record badges required for all attendees.",
    attendeeInformation: "Live check-in is ongoing at Hall 3 registration counter.",
    ticketTypes: [
      {
        id: "tt-401",
        name: "Expo Day Pass",
        price: "₹1,000",
        capacity: 500,
        sold: 480,
        status: "Selling Fast",
        description: "Full day access to expo hall and demonstrations.",
      },
    ],
    cancellationPolicy: {
      allowed: false,
      deadline: "Non-refundable",
      refundPolicy: "NO_REFUND",
      refundPercentage: 0,
    },
    contactInformation: {
      name: "Arjun Kumar",
      phone: "+91 98765 43210",
      email: "contact@buildershyderabad.io",
    },
  },
  {
    id: 5,
    name: "Indie Rock Live Showcase",
    short: "Indie Rock…",
    date: "20 Sep 2026",
    venue: "Mumbai",
    sold: 600,
    total: 600,
    pct: 100,
    revenue: "₹4,50,000",
    status: "COMPLETED",
    statusColor: "completed",
    category: "Music",
    ageRestriction: "18+",
    visibility: "PUBLIC",
    image: musicImg,
    thumbnail: musicImg,
    timeRange: "06:00 PM – 11:30 PM",
    duration: "5.5 Hours",
    isAllDay: false,
    locationType: "PHYSICAL",
    venueDetails: {
      name: "Bandra Amphitheatre",
      address: "Bandstand, Bandra West",
      city: "Mumbai",
      state: "Maharashtra",
      postalCode: "400050",
      country: "India",
    },
    description:
      "A sold-out evening celebrating the country's most compelling indie rock acts against the Mumbai sea breeze. Event concluded successfully with 600 attendees.",
    highlights: ["Sold out audience", "4 indie bands live on stage", "Acoustic open-air setup"],
    rules: "Event has concluded.",
    attendeeInformation: "Check-in closed. Post-event survey links have been emailed to attendees.",
    ticketTypes: [
      {
        id: "tt-501",
        name: "Standard Concert Pass",
        price: "₹750",
        capacity: 600,
        sold: 600,
        status: "Sold Out",
        description: "Amphitheatre entry pass.",
      },
    ],
    cancellationPolicy: {
      allowed: false,
      deadline: "Event completed",
      refundPolicy: "NO_REFUND",
      refundPercentage: 0,
    },
    contactInformation: {
      name: "Arjun Kumar",
      phone: "+91 98765 43210",
      email: "music@indierockmumbai.com",
    },
  },
  {
    id: 6,
    name: "Monsoon Food & Craft Fest",
    short: "Monsoon…",
    date: "05 Sep 2026",
    venue: "Kochi",
    sold: 0,
    total: 400,
    pct: 0,
    revenue: "₹0",
    status: "CANCELLED",
    statusColor: "cancelled",
    category: "Food & Drinks",
    ageRestriction: "All Ages",
    visibility: "PUBLIC",
    image: comedyImg,
    thumbnail: comedyImg,
    timeRange: "11:00 AM – 09:00 PM",
    duration: "10 Hours",
    isAllDay: false,
    locationType: "PHYSICAL",
    venueDetails: {
      name: "Durbar Hall Ground",
      address: "Ernakulam South",
      city: "Kochi",
      state: "Kerala",
      postalCode: "682016",
      country: "India",
    },
    description:
      "This outdoor festival was cancelled due to regional extreme monsoon weather alerts. Full automated refunds have been processed for all pre-registered attendees.",
    highlights: ["Full attendee refunds disbursed", "Safety postponement"],
    rules: "Event is cancelled.",
    attendeeInformation: "Please reach out to support for any queries regarding payment reversals.",
    ticketTypes: [
      {
        id: "tt-601",
        name: "Festival Tasting Pass",
        price: "₹250",
        capacity: 400,
        sold: 0,
        status: "Cancelled",
        description: "Includes food tasting vouchers.",
      },
    ],
    cancellationPolicy: {
      allowed: true,
      deadline: "Immediate refund",
      refundPolicy: "FULL",
      refundPercentage: 100,
    },
    contactInformation: {
      name: "Arjun Kumar",
      phone: "+91 98765 43210",
      email: "support@monsoonfest.in",
    },
  },
  {
    id: 7,
    name: "Creative Design & UX Masterclass",
    short: "Creative…",
    date: "18 Oct 2026",
    venue: "Bengaluru",
    sold: 180,
    total: 200,
    pct: 90,
    revenue: "₹1,80,000",
    status: "PUBLISHED",
    statusColor: "published",
    category: "Workshop",
    ageRestriction: "All Ages",
    visibility: "PUBLIC",
    image: workshopImg,
    thumbnail: workshopImg,
    timeRange: "10:00 AM – 04:00 PM",
    duration: "6 Hours",
    isAllDay: false,
    locationType: "PHYSICAL",
    venueDetails: {
      name: "Design Studio Hub",
      address: "Indiranagar 100ft Road",
      city: "Bengaluru",
      state: "Karnataka",
      postalCode: "560038",
      country: "India",
    },
    description:
      "An intensive design workshop focusing on design systems, Figma component architecture, and fluid micro-interactions for modern web applications.",
    highlights: ["Live design critiques", "Take-home component library", "Certificate of completion"],
    rules: "Bring your own laptop with Figma installed.",
    attendeeInformation: "High-speed Wi-Fi and power strips available at every seat.",
    ticketTypes: [
      {
        id: "tt-701",
        name: "Full Workshop Pass",
        price: "₹1,000",
        capacity: 200,
        sold: 180,
        status: "Selling Fast",
        description: "Access to workshop, materials, and lunch.",
      },
    ],
    cancellationPolicy: {
      allowed: true,
      deadline: "48 hours before event",
      refundPolicy: "FULL",
      refundPercentage: 100,
    },
    contactInformation: {
      name: "Arjun Kumar",
      phone: "+91 98765 43210",
      email: "workshops@designhub.blr",
    },
  },
  {
    id: 8,
    name: "Electronic Dance Night Goa",
    short: "EDM Night…",
    date: "15 Nov 2026",
    venue: "Goa",
    sold: 0,
    total: 800,
    pct: 0,
    revenue: "₹0",
    status: "DRAFT",
    statusColor: "draft",
    category: "Music",
    ageRestriction: "21+",
    visibility: "PRIVATE",
    image: musicImg,
    thumbnail: musicImg,
    timeRange: "08:00 PM – 04:00 AM",
    duration: "8 Hours",
    isAllDay: false,
    locationType: "PHYSICAL",
    venueDetails: {
      name: "Vagator Beach Arena",
      address: "Vagator Cliff",
      city: "Goa",
      state: "Goa",
      postalCode: "403509",
      country: "India",
    },
    description: "Sundowner to dawn electronic beach festival overlooking the Arabian Sea.",
    highlights: ["Beachside soundstage", "International DJs", "Laser and fireworks display"],
    rules: "Valid age proof mandatory.",
    attendeeInformation: "Shuttle bus passes will be offered separately.",
    ticketTypes: [
      {
        id: "tt-801",
        name: "Early Entry Pass",
        price: "₹1,200",
        capacity: 800,
        sold: 0,
        status: "Draft",
        description: "Entry before 09:30 PM.",
      },
    ],
    cancellationPolicy: {
      allowed: true,
      deadline: "7 days before event",
      refundPolicy: "FULL",
      refundPercentage: 100,
    },
    contactInformation: {
      name: "Arjun Kumar",
      phone: "+91 98765 43210",
      email: "contact@goanightlife.com",
    },
  },
  {
    id: 9,
    name: "Startup Pitch & Angel Mixer",
    short: "Startup…",
    date: "22 Oct 2026",
    venue: "Bengaluru",
    sold: 85,
    total: 100,
    pct: 85,
    revenue: "₹85,000",
    status: "PUBLISHED",
    statusColor: "published",
    category: "Conferences",
    ageRestriction: "All Ages",
    visibility: "PUBLIC",
    image: conferenceImg,
    thumbnail: conferenceImg,
    timeRange: "05:00 PM – 09:00 PM",
    duration: "4 Hours",
    isAllDay: false,
    locationType: "PHYSICAL",
    venueDetails: {
      name: "WeWork Galaxy",
      address: "Residency Road, Shanthala Nagar",
      city: "Bengaluru",
      state: "Karnataka",
      postalCode: "560025",
      country: "India",
    },
    description: "An exclusive evening connecting 15 curated seed-stage startups with active angel investors.",
    highlights: ["15 three-minute live pitches", "Investor speed networking", "Cocktails and dinner"],
    rules: "Pre-registration screening required for startup founders.",
    attendeeInformation: "Check-in starts at 04:30 PM at the 4th floor terrace.",
    ticketTypes: [
      {
        id: "tt-901",
        name: "Founder / Investor Seat",
        price: "₹1,000",
        capacity: 100,
        sold: 85,
        status: "Available",
        description: "Networking pass including food & drinks.",
      },
    ],
    cancellationPolicy: {
      allowed: true,
      deadline: "24 hours before event",
      refundPolicy: "FULL",
      refundPercentage: 100,
    },
    contactInformation: {
      name: "Arjun Kumar",
      phone: "+91 98765 43210",
      email: "pitch@angelblr.org",
    },
  },
  {
    id: 10,
    name: "City Marathon & Fitness Expo",
    short: "Marathon…",
    date: "08 Nov 2026",
    venue: "Bengaluru",
    sold: 1250,
    total: 1500,
    pct: 83,
    revenue: "₹6,25,000",
    status: "PUBLISHED",
    statusColor: "published",
    category: "Sports",
    ageRestriction: "12+",
    visibility: "PUBLIC",
    image: sportsImg,
    thumbnail: sportsImg,
    timeRange: "05:30 AM – 11:30 AM",
    duration: "6 Hours",
    isAllDay: false,
    locationType: "PHYSICAL",
    venueDetails: {
      name: "Kanteerava Stadium",
      address: "Kasturba Road, Sampangi Rama Nagar",
      city: "Bengaluru",
      state: "Karnataka",
      postalCode: "560001",
      country: "India",
    },
    description: "Annual city half-marathon, 10K run, and 5K fun run promoting fitness, community, and clean green city initiatives.",
    highlights: ["Timed bib and RFID tracking", "Finisher medal & dri-fit running tee", "Hydration and medical stations every 1.5km"],
    rules: "Medical disclaimer required upon registration.",
    attendeeInformation: "Bib collection expo held 2 days prior to race day.",
    ticketTypes: [
      {
        id: "tt-1001",
        name: "10K Timed Run",
        price: "₹500",
        capacity: 1500,
        sold: 1250,
        status: "Available",
        description: "Includes race kit, timing chip, and breakfast.",
      },
    ],
    cancellationPolicy: {
      allowed: true,
      deadline: "7 days before event",
      refundPolicy: "PARTIAL",
      refundPercentage: 80,
    },
    contactInformation: {
      name: "Arjun Kumar",
      phone: "+91 98765 43210",
      email: "run@bangaloremarathon.org",
    },
  },
  {
    id: 11,
    name: "Modern Web Development Bootcamp",
    short: "Web Dev…",
    date: "25 Oct 2026",
    venue: "Online",
    sold: 290,
    total: 300,
    pct: 97,
    revenue: "₹1,45,000",
    status: "PUBLISHED",
    statusColor: "published",
    category: "Workshop",
    ageRestriction: "All Ages",
    visibility: "PUBLIC",
    image: techImg,
    thumbnail: techImg,
    timeRange: "02:00 PM – 06:00 PM",
    duration: "4 Hours",
    isAllDay: false,
    locationType: "ONLINE",
    venueDetails: {
      name: "Virtual Interactive Live Stream",
      address: "Zoom Video Webinar",
      city: "Online",
      state: "Virtual",
      postalCode: "N/A",
      country: "Worldwide",
    },
    description: "Live interactive online masterclass covering modern React 19 architecture, Vite build pipelines, Tailwind CSS v4, and state management patterns.",
    highlights: ["Live code along session", "Discord community channel access", "Session recordings available indefinitely"],
    rules: "Participants must have basic JavaScript knowledge.",
    attendeeInformation: "Stream link and repository starter will be emailed 1 hour before session.",
    ticketTypes: [
      {
        id: "tt-1101",
        name: "Virtual Pass",
        price: "₹500",
        capacity: 300,
        sold: 290,
        status: "Selling Fast",
        description: "Live webinar link + full source code access.",
      },
    ],
    cancellationPolicy: {
      allowed: true,
      deadline: "24 hours before event",
      refundPolicy: "FULL",
      refundPercentage: 100,
    },
    contactInformation: {
      name: "Arjun Kumar",
      phone: "+91 98765 43210",
      email: "bootcamp@eventhub.com",
    },
  },
  {
    id: 12,
    name: "Contemporary Art & Sculpture Gallery",
    short: "Art Gallery…",
    date: "30 Nov 2026",
    venue: "Kochi",
    sold: 0,
    total: 250,
    pct: 0,
    revenue: "₹0",
    status: "DRAFT",
    statusColor: "draft",
    category: "Art & Culture",
    ageRestriction: "All Ages",
    visibility: "PRIVATE",
    image: workshopImg,
    thumbnail: workshopImg,
    timeRange: "11:00 AM – 07:00 PM",
    duration: "8 Hours",
    isAllDay: true,
    locationType: "PHYSICAL",
    venueDetails: {
      name: "Fort Kochi Heritage Hall",
      address: "Bazaar Road, Mattancherry",
      city: "Kochi",
      state: "Kerala",
      postalCode: "682002",
      country: "India",
    },
    description: "An exhibition celebrating south Indian contemporary sculptors and mixed-media oil artists.",
    highlights: ["Artist meet-and-greet sessions", "Live ceramic making booth", "Curated collector preview"],
    rules: "No flash photography allowed inside exhibition rooms.",
    attendeeInformation: "Audio guide devices provided at the reception desk.",
    ticketTypes: [
      {
        id: "tt-1201",
        name: "General Exhibition Entry",
        price: "₹200",
        capacity: 250,
        sold: 0,
        status: "Draft",
        description: "Standard gallery day pass.",
      },
    ],
    cancellationPolicy: {
      allowed: true,
      deadline: "24 hours before event",
      refundPolicy: "FULL",
      refundPercentage: 100,
    },
    contactInformation: {
      name: "Arjun Kumar",
      phone: "+91 98765 43210",
      email: "curator@fortkochigallery.in",
    },
  },
];

export const TABS_CONFIG = [
  { label: "All Events", value: "ALL", filter: () => true },
  { label: "Drafts", value: "DRAFT", filter: (e) => e.status === "DRAFT" },
  { label: "Published", value: "PUBLISHED", filter: (e) => e.status === "PUBLISHED" },
  { label: "Ongoing", value: "ONGOING", filter: (e) => e.status === "ONGOING" },
  { label: "Completed", value: "COMPLETED", filter: (e) => e.status === "COMPLETED" },
  { label: "Cancelled", value: "CANCELLED", filter: (e) => e.status === "CANCELLED" },
];

export function getOrganizerEventById(id) {
  if (!id) return ORGANIZER_EVENTS[0];
  const numId = Number(id);
  const found = ORGANIZER_EVENTS.find((e) => e.id === numId || String(e.id) === String(id));
  return found || ORGANIZER_EVENTS[0];
}
